### ISSUE TITLE
Error ketika simpan karyawn

### ISSUE THREAD

**Issue by triandamai** [raflyfirdausy/star-cell#1]
2019-05-29 07:21:05.514 19964-19964/com.rfl.trn.starr_cell E/RecyclerView: No adapter attached; skipping layout
2019-05-29 07:21:26.700 19964-19964/com.rfl.trn.starr_cell E/WindowManager: android.view.WindowLeaked: Activity com.rfl.trn.starr_cell.Activity.TambahKaryawanActivity has leaked window DecorView@1bb8db8[TambahKaryawanActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:518)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at com.rfl.trn.starr_cell.Activity.TambahKaryawanActivity.simpanKeDatabase(TambahKaryawanActivity.java:159)
        at com.rfl.trn.starr_cell.Activity.TambahKaryawanActivity.access$000(TambahKaryawanActivity.java:58)
        at com.rfl.trn.starr_cell.Activity.TambahKaryawanActivity$1.onClick(TambahKaryawanActivity.java:134)
        at com.ontbee.legacyforks.cn.pedant.SweetAlert.SweetAlertDialog.onClick(SweetAlertDialog.java:373)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25945)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by triandamai** [comment]
ketmeu dengan membuat loading dialog global 
`private SweetAlertDialog dialog`

**Comment by triandamai** [comment]
oke
